language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed nguoidang1996/udagram-api-feed:v1
  - docker tag udagram-api-user nguoidang1996/udagram-api-user:v1
  - docker tag udagram-frontend nguoidang1996/udagram-frontend:v1
  - docker tag udagram-reverseproxy nguoidang1996/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nguoidang1996/udagram-api-feed:v1
  - docker push nguoidang1996/udagram-api-user:v1
  - docker push nguoidang1996/udagram-frontend:v1
  - docker push nguoidang1996/udagram-reverseproxy:v1
